using DinkToPdf;
using SelectPdf;
using System;

namespace pdftest.Core.PdfRenderers
{
    public class SelectPdfService
    {
        public void Generate(string htmlContent, string headerContent)
        {
            // Create a new HTML to PDF converter
            HtmlToPdf converter = new HtmlToPdf();

            // Configure the PDF settings
            converter.Options.MarginTop = 50;    // Leave space for the header
            converter.Options.MarginBottom = 50; // Leave space for the footer
            converter.Options.MarginLeft = 20;
            converter.Options.MarginRight = 20;

            // Add a header to the PDF
            converter.Options.DisplayHeader = true;
            converter.Header.DisplayOnFirstPage = true;
            converter.Header.DisplayOnOddPages = true;
            converter.Header.DisplayOnEvenPages = true;
            converter.Header.Height = 50;

            // Add content to the header
            PdfHtmlSection headerHtml = new PdfHtmlSection(headerContent, string.Empty);
            headerHtml.AutoFitHeight = HtmlToPdfPageFitMode.AutoFit;
            converter.Header.Add(headerHtml);

            // Add a footer to the PDF
            converter.Options.DisplayFooter = true;
            converter.Footer.DisplayOnFirstPage = true;
            converter.Footer.DisplayOnOddPages = true;
            converter.Footer.DisplayOnEvenPages = true;
            converter.Footer.Height = 50;

            // Add a styled HTML footer section
            string footerHtml = @"
            <div style='text-align:left; font-size:12px;'>
                <b>Generated by:</b> My Application
            </div>";
            PdfHtmlSection footerHtmlSection = new PdfHtmlSection(footerHtml, string.Empty);
            footerHtmlSection.AutoFitHeight = HtmlToPdfPageFitMode.AutoFit;
            converter.Footer.Add(footerHtmlSection);

            // Add a text footer section for page numbering
            PdfTextSection footerPageNumbers = new PdfTextSection(0, 40, "Page {page_number} of {total_pages}", new System.Drawing.Font("Arial", 10));
            footerPageNumbers.HorizontalAlign = PdfTextHorizontalAlign.Center;
            converter.Footer.Add(footerPageNumbers);

            // Generate the PDF
            PdfDocument pdfDocument = converter.ConvertHtmlString(htmlContent);

            // Save the PDF to a file
            string filePath = "sample-SelectPdf.pdf";
            pdfDocument.Save(filePath);

            // Close the PDF document
            pdfDocument.Close();

            Console.WriteLine($"PDF created successfully: {filePath}");
        }
    }
}
